services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - 127.0.0.1:8080:8080
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      JWT_SECRET: ${JWT_SECRET}
      WEATHER_API_USERNAME: ${WEATHER_API_USERNAME}
      WEATHER_API_PASSWORD: ${WEATHER_API_PASSWORD}
      FE_URL: ${FE_URL}
      AI_URL: ${AI_URL}